import { auth } from "@/lib/auth";
import { getAuthUrl, isMcpEnabled } from "@/lib/env";

/** Root alias for the metadata generated by Better Auth's MCP plugin. */
export async function GET(request: Request = new Request(getAuthUrl())) {
  if (!isMcpEnabled()) return new Response(null, { status: 404 });
  const metadataUrl = new URL("/.well-known/oauth-protected-resource/mcp", getAuthUrl());
  return auth.handler(new Request(metadataUrl, { headers: request.headers }));
}
